apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: trail
      defaultBucket: paxcounter
      tlsSkipVerify: true
    secureJsonData:
      token: changeme-please-token
    isDefault: true
    editable: true
